name: Build and Upload to Release

on:
  release:
    types: [ created, published ]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Remplacement des variables de connexion
      - name: Update database connection variables
        run: |
          $path = "CS_Winform_ESIEE/Data/DatabaseConnector.cs"
          $content = Get-Content $path
          $content = $content -replace '@server";', '${{ secrets.DATABASE_HOST }}";'
          $content = $content -replace '@database";', '${{ secrets.DATABASE_NAME }}";'
          $content = $content -replace '@user";', '${{ secrets.DATABASE_USER }}";'
          $content = $content -replace '@password";', '${{ secrets.DATABASE_PASSWORD }}";'
          Set-Content -Path $path -Value $content

      # Étape 3 : Installation de MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Étape 4 : Installation de NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.0

      # Étape 5 : Restauration des dépendances
      - name: Restore dependencies
        run: nuget restore CS_Winform_ESIEE.sln

      # Étape 6 : Compilation du projet
      - name: Build solution
        run: msbuild CS_Winform_ESIEE.sln /p:Configuration=Release /p:Platform="Any CPU" /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishDir=CS_Winform_ESIEE/bin/Release/

      # Étape 7 : Téléchargement de l'exécutable dans la release
      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: CS_Winform_ESIEE/bin/Release/CS_Winform_ESIEE.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 8 : Suppression du dossier Release
      - name: Remove Release folder
        run: Remove-Item -Path CS_Winform_ESIEE/bin/Release -Recurse -Force

      # Étape 9 : Recompilation en mode multi-fichier
      - name: Build solution in multi-file
        run: msbuild CS_Winform_ESIEE.sln /p:Configuration=Release /p:Platform="Any CPU" /p:PublishDir=CS_Winform_ESIEE/bin/Release/

      # Étape 10 : Téléchargement des fichiers multi-fichiers dans la release
      - name: Upload multi-file to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CS_Winform_ESIEE/bin/Release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
