name: Build and Create .exe

on:
  push:
    branches:
      - main
      - dev
      - feature/*
  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Étape 2 : Changer les variables par défaut (@server, @database, @user, @password) de la base dans le fichier DatabaseConnection.cs par les secrets
      - name: Change default variables
        run: |
          $path = "CS_Winform_ESIEE/Data/DatabaseConnector.cs"
          $content = Get-Content $path
          $content = $content -replace '@server";', '${{ secrets.DATABASE_HOST }}";'
          $content = $content -replace '@database";', '${{ secrets.DATABASE_NAME }}";'
          $content = $content -replace '@user";', '${{ secrets.DATABASE_USER }}";'
          $content = $content -replace '@password";', '${{ secrets.DATABASE_PASSWORD }}";'
          Set-Content -Path $path -Value $content
        
      # Étape 3 : Installation de .NET Framework
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Étape 4 : Installation NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.0

      # Étape 5 : Restauration des dépendances
      - name: Restore dependencies
        run: nuget restore CS_Winform_ESIEE.sln

      # Étape 6 : Compilation du projet
      - name: Build solution
        run: msbuild CS_Winform_ESIEE.sln /p:Configuration=Release /p:Platform="Any CPU"

      # Étape 7 : Archivage de l'exécutable
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: CS_Winform_ESIEE
          path: CS_Winform_ESIEE/bin/Release/
